### ISSUE TITLE
support huge git repositories

### ISSUE THREAD

**Issue by maxogden** [maxogden/taco#11]
I learned in the saga that was https://github.com/substack/git-http-backend/issues/4 that the way we are spawning `--stateless-rpc` git processes to receive pushes causes weird bugs with git, particularly with large git repositories.

We should switch over to use pre-receive git hooks that spawn blocking processes instead, e.g. the way dokku does it: https://github.com/progrium/dokku/blob/master/plugins/git/commands#L38-L55

This would mean that instead of us spawning git, git would spawn us. This could either happen as a new module or inside git-http-backend, i'm not sure where exactly it should live yet

**Comment by maxogden** [comment]
this issue not relevant anymore in taco v2 (we use tarballs now)

**Comment by tadatuta** [comment]
@maxogden is `v2` already usable or just a WIP?

**Comment by max-mapper** [comment]
@tadatuta it's usable, but a breaking change from v1. see the readme for example usage

**Comment by tadatuta** [comment]
thank you!
